Vagrant.configure("2") do |config|
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.box = 'ubuntu/trusty64'
  config.vm.host_name = 'l56.root-servers'
  config.vm.network "forwarded_port", guest: 53, host: 5353, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 53, host: 5353, protocol: "udp" 

  config.vm.provision "shell", inline: "wget https://apt.puppetlabs.com/puppet5-release-trusty.deb"
  config.vm.provision "shell", inline: "dpkg -i puppet5-release-trusty.deb"
  config.vm.provision "shell", inline: "apt-get update"
  config.vm.provision "shell", inline: "apt-get -y upgrade"
  config.vm.provision "shell", inline: "apt-get install -y puppet-agent python-dnspython"
  config.vm.provision "shell", inline: "/vagrant/fetch_zone.sh"

  config.vm.provision :puppet do |puppet|
    puppet.environment = 'production'
    puppet.environment_path = 'puppet/environments'
    puppet.hiera_config_path = "puppet/hiera.yaml"
    puppet.module_path = "../modules"
  end
end
